import assert from "node:assert/strict";
import {searchLinguisticKnowledge,getCorrectionRuleSet,getGlobalKnowledgeStats,getLearningDepth,getActivityBlueprint} from "../src/linguistic-knowledge-index.js";
import {getLinguisticResourcesForActivity} from "../src/linguistic-activity-links.js";
import {analyzeLanguage} from "../src/linguistic-engine.js";
const stats=getGlobalKnowledgeStats();
assert.ok(stats.grammarRules>=80);
assert.ok(stats.vocabularyEntries>=300,"expanded vocabulary should be globally indexed");
assert.equal(stats.globalAvailability,true);
assert.equal(stats.activityIndependentCorrection,true);
assert.ok(stats.indexedTokens>1000);
import catalog from "../data/linguistic-catalog.json" with { type: "json" };
assert.ok([...catalog.grammarRules,...catalog.vocabularyEntries,...catalog.communicativeFunctions].every(x=>!Array.isArray(x.depthProfile?.stages)),"depth stage definitions must be normalized to a shared stage set");
assert.ok(searchLinguisticKnowledge("present perfect",{types:["grammar"],includeDrafts:true,limit:100}).some(x=>x.status==="draft"),"draft rules must be searchable");
assert.ok(searchLinguisticKnowledge("repositor",{types:["vocabulary"]}).some(x=>x.lemma==="repository"),"prefix search should find vocabulary");
assert.ok(searchLinguisticKnowledge("contraargumento",{types:["vocabulary"]}).some(x=>x.lemma==="counterargument"),"Spanish meaning should be searchable");
const corrections=getCorrectionRuleSet();assert.ok(corrections.length>=20);assert.ok(corrections.every(x=>x.status==="tested"));
const result=analyzeLanguage("She work at a school.");assert.ok(result.errors.length>0,"correction must work without an activity id");assert.notEqual(result.correctedText,"She work at a school.");
const activity=getLinguisticResourcesForActivity({id:"UNLINKED-OPEN-WRITING",skill:"writing",level:"A2",type:"independent-production",task:"Write anything you want about your work.",tags:[]});
assert.equal(activity.knowledgeAvailability,"global");assert.equal(activity.correctionIndependentOfActivity,true);assert.deepEqual(activity.correctionRuleIds,corrections.map(x=>x.id));assert.ok(activity.activityBlueprint.primaryModes.includes("edit-a-draft"));assert.ok(activity.knowledgeSearchResults.length>0);
assert.ok(getActivityBlueprint("grammar","B2").primaryModes.includes("explain-why"));
assert.equal(getLearningDepth({level:"B2"},"A2").maxDepth,"recognition");assert.equal(getLearningDepth({level:"B2"},"A2").availableForCorrection,true);assert.equal(getLearningDepth({level:"A1"},"B2",{mastery:.9}).maxDepth,"transfer");
console.log("HODIE global linguistic knowledge index: PASS",JSON.stringify(stats));
