import assert from "node:assert/strict";
import { analyzeLanguage, validateLinguisticCatalog } from "../src/linguistic-engine.js";
import { auditActivityCoverage } from "../src/linguistic-activity-links.js";
import catalog from "../data/linguistic-catalog.json" with { type: "json" };
const validation=validateLinguisticCatalog(catalog);assert.equal(validation.valid,true,validation.errors.join("\n"));
const audit=auditActivityCoverage();assert.equal(audit.unlinked.length,0,"Unlinked activities: "+audit.unlinked.join(", "));assert.equal(audit.linked,audit.total);assert.ok(audit.directCanDo>0);
const activeIds=["PLURAL-COUNT-001","THERE-BE-COUNT-001","DOES-BASE-001","MODAL-BASE-001","PAST-DID-BASE-001","PRES-CONT-BASE-001"];
const lifecycleIds=[...activeIds,"GRAM-B1-FIRST-CONDITIONAL-002","GRAM-B1-CONNECTORS-002","GRAM-B2-ARGUMENT-CLAIMS-001","GRAM-B2-COHESION-001",...["GRAM-SUBJECT-PRONOUNS-001","GRAM-QUESTION-001","GRAM-PREP-TIME-001","GRAM-PREP-PLACE-001","GRAM-PRES-PERF-001","GRAM-PASSIVE-001","GRAM-INDIRECT-QUESTION-001","GRAM-DO-QUESTIONS-001","GRAM-PLURAL-S-001","GRAM-ARTICLE-GENERAL-001","GRAM-OBJECT-PRONOUN-001","GRAM-SINCE-FOR-001","GRAM-ALTHOUGH-001","GRAM-COND-001"]];
for(const id of lifecycleIds){const r=catalog.grammarRules.find(x=>x.id===id);assert.ok(r?.exceptions?.length&&r.negativeCases?.length&&r.practice?.length&&r.activityLinks?.skills?.length,id+" incomplete metadata");assert.ok(r.examplesBilingual?.every(x=>x.en&&x.es),id+" missing bilingual examples");}
for(const id of activeIds){const r=catalog.grammarRules.find(x=>x.id===id);assert.equal(r.status,"tested",id);assert.ok(audit.rows.some(x=>x.ruleIds.includes(id)),id+" not linked to an activity");}
for(const id of ["GRAM-SUBJECT-PRONOUNS-001","GRAM-QUESTION-001","GRAM-PREP-TIME-001","GRAM-PREP-PLACE-001","GRAM-PRES-PERF-001","GRAM-PASSIVE-001","GRAM-INDIRECT-QUESTION-001","GRAM-DO-QUESTIONS-001","GRAM-PLURAL-S-001","GRAM-ARTICLE-GENERAL-001","GRAM-OBJECT-PRONOUN-001","GRAM-SINCE-FOR-001","GRAM-ALTHOUGH-001","GRAM-COND-001"]){assert.ok(audit.rows.some(x=>x.ruleIds.includes(id)),id+" not linked to an activity");assert.equal(catalog.grammarRules.find(x=>x.id===id).status,"draft",id+" must remain inactive until tested");}
for(const t of catalog.testCases.filter(x=>x.id.startsWith("TC-PLURAL-COUNT-")||x.id.startsWith("TC-THERE-BE-")||x.id.startsWith("TC-DOES-BASE-")||x.id.startsWith("TC-MODAL-BASE-")||x.id.startsWith("TC-PAST-DID-")||x.id.startsWith("TC-PRES-CONT-"))){const result=analyzeLanguage(t.text);assert.deepEqual(result.errors.map(e=>e.ruleId),t.expectRules,t.id);assert.equal(result.correctedText,t.expectCorrection,t.id);}
assert.equal(analyzeLanguage("I am ready.").errors.length,0);assert.equal(analyzeLanguage("She can build a robot.").errors.length,0);
console.log("HODIE activity linkage and CEFR contrastive coverage: PASS",JSON.stringify({total:audit.total,linked:audit.linked,directCanDo:audit.directCanDo,tagLinked:audit.tagLinked,levelFallback:audit.levelFallback,activeRules:activeIds.length,draftRules:lifecycleIds.length+4}));
